repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: check-merge-conflict
      - id: detect-private-key

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.7.0
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
        files: ^pipeline/
      - id: ruff-format
        files: ^pipeline/

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.13.0
    hooks:
      - id: mypy
        files: ^pipeline/
        args: [--strict]

  - repo: https://github.com/trufflesecurity/trufflehog
    rev: v3.82.2
    hooks:
      - id: trufflehog
        entry: trufflehog git
        args: [--only-verified]
