'use client'

import { useMemo, useState } from 'react'
import Link from 'next/link'
import { ChevronRight, ReceiptText } from 'lucide-react'

import { InvoiceStatusChip } from '@/components/invoices/invoice-status-chip'
import type { InvoiceStatus } from '@/components/invoices/format'
import {
  Table,
  TableBody,
  TableCell,
  TableFooter,
  TableHead,
  TableHeader,
  TableRow,
} from '@/components/ui/table'
import { monthLabel } from '@/shared/lib/date-display'
import { cn } from '@/shared/lib/utils'

import { fullDateLabel, moneyLabel } from './format'

/**
 * The client billing timeline (C16, 01:33:59): the QBO-style chronological
 * money history for one client - every invoice, newest first, sortable by
 * date or amount, with a type chip (recurring run vs one-off), the status
 * chip, sent/paid dates, expandable line items per row, and footer totals.
 * Money is numeric strings rendered right-aligned in tabular numerals; the
 * data is composed server-side (owner/admin only) and never computed here.
 */

export interface ClientInvoiceLineRef {
  id: number
  lineType: string
  description: string
  /** Numeric strings from Postgres - formatted, never computed on. */
  quantity: string
  unitPrice: string
  discount: string
  amount: string
}

export interface ClientInvoiceTimelineItem {
  id: number
  invoiceNumber: string
  status: InvoiceStatus
  year: number | null
  month: number | null
  /** true for the monthly generated run; false for one-off/milestone rows. */
  isAutoGenerated: boolean
  total: string
  issueDate: string | null
  dueDate: string | null
  /** ISO timestamps (or null); rendered as dates. */
  sentAt: string | null
  paidAt: string | null
  lines: ClientInvoiceLineRef[]
}

type SortKey = 'date' | 'total'
type SortDir = 'asc' | 'desc'

/** Stable chronological key: issue date, then id as the tiebreaker. */
function dateKey(inv: ClientInvoiceTimelineItem): string {
  return `${inv.issueDate ?? '0000-00-00'}:${String(inv.id).padStart(10, '0')}`
}

/** Timestamp -> "Aug 30, 2026" (ISO string through Intl, matching billing-panel). */
function stampDateLabel(iso: string): string {
  return new Intl.DateTimeFormat('en-US', { month: 'short', day: 'numeric', year: 'numeric' }).format(
    new Date(iso),
  )
}

function SortableHead({
  label,
  sortKey,
  sort,
  onSort,
  className,
}: {
  label: string
  sortKey: SortKey
  sort: { key: SortKey; dir: SortDir }
  onSort: (key: SortKey) => void
  className?: string
}) {
  const active = sort.key === sortKey
  return (
    <TableHead
      className={cn('h-9 px-3 text-[11px] font-semibold uppercase tracking-wider', className)}
      aria-sort={active ? (sort.dir === 'desc' ? 'descending' : 'ascending') : undefined}
    >
      <button
        type="button"
        onClick={() => onSort(sortKey)}
        data-testid={`sort-${sortKey}`}
        className="inline-flex items-center gap-1 uppercase tracking-wider transition-colors hover:text-foreground focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-ring"
      >
        {label}
        <span aria-hidden className={cn('text-[9px]', active ? 'text-foreground' : 'text-muted-foreground/40')}>
          {active && sort.dir === 'asc' ? '▲' : '▼'}
        </span>
      </button>
    </TableHead>
  )
}

export function BillingTimeline({ invoices }: { invoices: ClientInvoiceTimelineItem[] }) {
  const [sort, setSort] = useState<{ key: SortKey; dir: SortDir }>({ key: 'date', dir: 'desc' })
  const [expanded, setExpanded] = useState<Set<number>>(new Set())

  const sorted = useMemo(() => {
    const rows = [...invoices]
    rows.sort((a, b) => {
      const cmp =
        sort.key === 'date'
          ? dateKey(a).localeCompare(dateKey(b))
          : Number(a.total) - Number(b.total)
      return sort.dir === 'asc' ? cmp : -cmp
    })
    return rows
  }, [invoices, sort])

  // QBO-style summary strip: billed (void excluded), outstanding, paid.
  const totals = useMemo(() => {
    const billed = invoices.filter((i) => i.status !== 'void')
    const cents = (rows: ClientInvoiceTimelineItem[]) =>
      rows.reduce((sum, i) => sum + Math.round(Number(i.total) * 100), 0)
    return {
      billedCents: cents(billed),
      outstandingCents: cents(billed.filter((i) => i.status === 'sent' || i.status === 'overdue')),
      paidCents: cents(billed.filter((i) => i.status === 'paid')),
      count: billed.length,
    }
  }, [invoices])

  function toggleSort(key: SortKey) {
    setSort((prev) =>
      prev.key === key
        ? { key, dir: prev.dir === 'desc' ? 'asc' : 'desc' }
        : { key, dir: 'desc' },
    )
  }

  function toggleExpanded(id: number) {
    setExpanded((prev) => {
      const next = new Set(prev)
      if (next.has(id)) next.delete(id)
      else next.add(id)
      return next
    })
  }

  return (
    <section aria-label="Billing history" className="space-y-2" data-testid="billing-timeline">
      <h3 className="flex items-baseline gap-2 text-xs font-bold uppercase tracking-wider text-muted-foreground">
        Billing history
        <span className="tnum font-semibold">{invoices.length}</span>
      </h3>

      {invoices.length === 0 ? (
        <p className="rounded-xl border border-dashed border-border bg-card px-4 py-4 text-xs text-muted-foreground">
          No invoices yet - they appear here after the monthly billing run.
        </p>
      ) : (
        <>
          <div className="grid grid-cols-3 gap-2" data-testid="billing-timeline-summary">
            <div className="rounded-lg border border-border bg-card px-3 py-2">
              <div className="text-[11px] font-medium text-muted-foreground">Billed</div>
              <div className="tnum mt-0.5 text-sm font-semibold text-foreground">
                {moneyLabel((totals.billedCents / 100).toFixed(2))}
              </div>
            </div>
            <div className="rounded-lg border border-border bg-card px-3 py-2">
              <div className="text-[11px] font-medium text-muted-foreground">Outstanding</div>
              <div className="tnum mt-0.5 text-sm font-semibold text-money-strong">
                {moneyLabel((totals.outstandingCents / 100).toFixed(2))}
              </div>
            </div>
            <div className="rounded-lg border border-border bg-card px-3 py-2">
              <div className="text-[11px] font-medium text-muted-foreground">Paid</div>
              <div className="tnum mt-0.5 text-sm font-semibold text-status-on-track">
                {moneyLabel((totals.paidCents / 100).toFixed(2))}
              </div>
            </div>
          </div>

          <div className="overflow-hidden rounded-xl border border-border bg-card">
            <Table>
              <TableHeader>
                <TableRow className="hover:bg-transparent">
                  <TableHead className="h-9 w-8 px-2" />
                  <TableHead className="h-9 px-3 text-[11px] font-semibold uppercase tracking-wider">
                    Invoice
                  </TableHead>
                  <SortableHead label="Date" sortKey="date" sort={sort} onSort={toggleSort} />
                  <TableHead className="h-9 px-3 text-[11px] font-semibold uppercase tracking-wider">
                    Type
                  </TableHead>
                  <TableHead className="h-9 px-3 text-[11px] font-semibold uppercase tracking-wider">
                    Status
                  </TableHead>
                  <TableHead className="h-9 px-3 text-[11px] font-semibold uppercase tracking-wider">
                    Sent / Paid
                  </TableHead>
                  <SortableHead
                    label="Total"
                    sortKey="total"
                    sort={sort}
                    onSort={toggleSort}
                    className="text-right"
                  />
                </TableRow>
              </TableHeader>
              <TableBody>
                {sorted.map((inv) => {
                  const isOpen = expanded.has(inv.id)
                  return (
                    <TimelineRow
                      key={inv.id}
                      invoice={inv}
                      expanded={isOpen}
                      onToggle={() => toggleExpanded(inv.id)}
                    />
                  )
                })}
              </TableBody>
              <TableFooter className="bg-muted/50">
                <TableRow className="hover:bg-transparent" data-testid="billing-timeline-totals">
                  <TableCell className="px-3 py-2" colSpan={6}>
                    <span className="text-xs font-semibold text-foreground">Total billed</span>
                    <span className="ml-2 text-[11px] text-muted-foreground">
                      {totals.count} invoice{totals.count === 1 ? '' : 's'}, void excluded
                    </span>
                  </TableCell>
                  <TableCell className="tnum px-3 py-2 text-right text-sm font-bold text-foreground">
                    {moneyLabel((totals.billedCents / 100).toFixed(2))}
                  </TableCell>
                </TableRow>
              </TableFooter>
            </Table>
          </div>
        </>
      )}
    </section>
  )
}

function TimelineRow({
  invoice,
  expanded,
  onToggle,
}: {
  invoice: ClientInvoiceTimelineItem
  expanded: boolean
  onToggle: () => void
}) {
  return (
    <>
      <TableRow data-testid="billing-timeline-row" data-invoice-id={invoice.id} className="h-11">
        <TableCell className="px-2 py-0">
          <button
            type="button"
            onClick={onToggle}
            aria-expanded={expanded}
            aria-label={`${expanded ? 'Collapse' : 'Expand'} line items for ${invoice.invoiceNumber}`}
            data-testid="billing-timeline-expand"
            className="rounded p-1 text-muted-foreground transition-colors hover:bg-muted hover:text-foreground focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-ring"
          >
            <ChevronRight
              className={cn('h-3.5 w-3.5 transition-transform duration-150', expanded && 'rotate-90')}
              aria-hidden
            />
          </button>
        </TableCell>
        <TableCell className="px-3 py-0">
          <Link
            href={`/invoices/${invoice.id}`}
            className="tnum whitespace-nowrap text-sm font-medium text-foreground underline-offset-4 hover:underline"
          >
            {invoice.invoiceNumber}
          </Link>
        </TableCell>
        <TableCell className="px-3 py-0">
          <span className="tnum whitespace-nowrap text-xs text-muted-foreground">
            {invoice.issueDate ? fullDateLabel(invoice.issueDate) : 'Not issued'}
          </span>
          {invoice.year != null && invoice.month != null && (
            <span className="tnum ml-1.5 shrink-0 rounded bg-muted px-1.5 py-0.5 text-[10px] font-semibold uppercase tracking-wide text-muted-foreground">
              {monthLabel(invoice.year, invoice.month)}
            </span>
          )}
        </TableCell>
        <TableCell className="px-3 py-0">
          <span
            className={cn(
              'rounded px-1.5 py-0.5 text-[10px] font-semibold uppercase tracking-wide',
              invoice.isAutoGenerated
                ? 'bg-accent text-accent-foreground'
                : 'bg-muted text-muted-foreground',
            )}
          >
            {invoice.isAutoGenerated ? 'Recurring' : 'One-off'}
          </span>
        </TableCell>
        <TableCell className="px-3 py-0">
          <InvoiceStatusChip status={invoice.status} />
        </TableCell>
        <TableCell className="px-3 py-0">
          <span className="tnum whitespace-nowrap text-xs text-muted-foreground">
            {invoice.sentAt ? stampDateLabel(invoice.sentAt) : 'Not sent'}
            {invoice.paidAt ? ` · Paid ${stampDateLabel(invoice.paidAt)}` : ''}
          </span>
        </TableCell>
        <TableCell
          className={cn(
            'tnum px-3 py-0 text-right text-sm font-semibold',
            invoice.status === 'void' ? 'text-muted-foreground line-through' : 'text-foreground',
          )}
        >
          {moneyLabel(invoice.total)}
        </TableCell>
      </TableRow>
      {expanded && (
        <TableRow className="bg-muted/30 hover:bg-muted/30" data-testid="billing-timeline-lines">
          <TableCell colSpan={7} className="px-4 py-3">
            {invoice.lines.length === 0 ? (
              <p className="text-xs text-muted-foreground">No line items on this invoice.</p>
            ) : (
              <table className="w-full text-xs">
                <thead>
                  <tr className="text-left text-[10px] font-semibold uppercase tracking-wider text-muted-foreground">
                    <th className="pb-1.5 pr-4 font-semibold">Line item</th>
                    <th className="tnum pb-1.5 pr-4 text-right font-semibold">Qty</th>
                    <th className="tnum pb-1.5 pr-4 text-right font-semibold">Unit price</th>
                    <th className="tnum pb-1.5 pr-4 text-right font-semibold">Discount</th>
                    <th className="tnum pb-1.5 text-right font-semibold">Amount</th>
                  </tr>
                </thead>
                <tbody>
                  {invoice.lines.map((line) => (
                    <tr key={line.id} className="border-t border-border/60">
                      <td className="py-1.5 pr-4 text-foreground">{line.description}</td>
                      <td className="tnum py-1.5 pr-4 text-right text-muted-foreground">
                        {Number(line.quantity)}
                      </td>
                      <td className="tnum py-1.5 pr-4 text-right text-muted-foreground">
                        {moneyLabel(line.unitPrice)}
                      </td>
                      <td className="tnum py-1.5 pr-4 text-right text-muted-foreground">
                        {Number(line.discount) !== 0 ? moneyLabel(line.discount) : '—'}
                      </td>
                      <td
                        className={cn(
                          'tnum py-1.5 text-right font-medium',
                          line.amount.startsWith('-') ? 'text-money-negative' : 'text-foreground',
                        )}
                      >
                        {moneyLabel(line.amount)}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            )}
          </TableCell>
        </TableRow>
      )}
    </>
  )
}
