/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/widgets/**/*.{js,ts,jsx,tsx,mdx}',
    './src/features/**/*.{js,ts,jsx,tsx,mdx}',
    './src/entities/**/*.{js,ts,jsx,tsx,mdx}',
    './src/shared/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        elite: {
          // Global palette
          black: '#000000',
          white: '#ffffff',
          'gray-100': '#f3f4f6',
          'gray-500': '#6b7280',
          'gray-900': '#111827',
          'blue-600': '#2563eb',
          'red-600': '#dc2626',
          // Semantic
          'text-primary': '#111827',
          'text-secondary': '#6b7280',
          background: '#ffffff',
          surface: '#f3f4f6',
          interactive: '#2563eb',
          danger: '#dc2626',
          success: '#16a34a',
          warning: '#d97706',
          border: '#e5e7eb',
        },
        // FirmOS semantic system — CSS-var backed so dark mode is free.
        firm: {
          brand: 'var(--firm-brand)',
          'brand-strong': 'var(--firm-brand-strong)',
          'brand-soft': 'var(--firm-brand-soft)',
          bg: 'var(--firm-bg)',
          surface: 'var(--firm-surface)',
          'surface-2': 'var(--firm-surface-2)',
          border: 'var(--firm-border)',
          'border-strong': 'var(--firm-border-strong)',
          text: 'var(--firm-text)',
          'text-2': 'var(--firm-text-2)',
          'text-3': 'var(--firm-text-3)',
        },
        status: {
          overdue: 'var(--status-overdue)',
          'overdue-bg': 'var(--status-overdue-bg)',
          'due-soon': 'var(--status-due-soon)',
          'due-soon-bg': 'var(--status-due-soon-bg)',
          'on-track': 'var(--status-on-track)',
          'on-track-bg': 'var(--status-on-track-bg)',
          deferred: 'var(--status-deferred)',
          'deferred-bg': 'var(--status-deferred-bg)',
          'waiting-client': 'var(--status-waiting-client)',
          'waiting-client-bg': 'var(--status-waiting-client-bg)',
          'on-hold': 'var(--status-on-hold)',
          'on-hold-bg': 'var(--status-on-hold-bg)',
        },
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        sm: '0.875rem',
        base: '1rem',
        lg: '1.125rem',
        xl: '1.25rem',
        '2xl': '1.5rem',
      },
      borderRadius: {
        sm: '0.25rem',
        md: '0.375rem',
        lg: '0.5rem',
      },
      spacing: {
        '01': '0.25rem',
        '02': '0.5rem',
        '03': '0.75rem',
        '04': '1rem',
        '05': '1.25rem',
        '06': '1.5rem',
        '08': '2rem',
        '10': '2.5rem',
        '12': '3rem',
      },
      boxShadow: {
        card: '0 1px 3px rgba(0, 0, 0, 0.1), 0 1px 2px rgba(0, 0, 0, 0.06)',
        modal: '0 20px 25px -5px rgba(0, 0, 0, 0.1), 0 10px 10px -5px rgba(0, 0, 0, 0.04)',
      },
    },
  },
  plugins: [],
}
