/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/page-views/**/*.{js,ts,jsx,tsx,mdx}',
    './src/widgets/**/*.{js,ts,jsx,tsx,mdx}',
    './src/features/**/*.{js,ts,jsx,tsx,mdx}',
    './src/entities/**/*.{js,ts,jsx,tsx,mdx}',
    './src/shared/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        // Foodcart global palette
        'fc-black': '#0a0a0a',
        'fc-white': '#ffffff',
        'fc-neutral-50': '#fafafa',
        'fc-neutral-100': '#f5f5f5',
        'fc-neutral-200': '#e5e5e5',
        'fc-neutral-300': '#d4d4d4',
        'fc-neutral-400': '#a3a3a3',
        'fc-neutral-500': '#737373',
        'fc-neutral-600': '#525252',
        'fc-neutral-700': '#404040',
        'fc-neutral-800': '#262626',
        'fc-neutral-900': '#171717',
        'fc-neutral-950': '#0a0a0a',
        'fc-cobalt-50': '#eff6ff',
        'fc-cobalt-100': '#dbeafe',
        'fc-cobalt-200': '#bfdbfe',
        'fc-cobalt-300': '#93c5fd',
        'fc-cobalt-400': '#60a5fa',
        'fc-cobalt-500': '#3b82f6',
        'fc-cobalt-600': '#2563eb',
        'fc-cobalt-700': '#1d4ed8',
        'fc-cobalt-800': '#1e40af',
        'fc-cobalt-900': '#1e3a8a',
        'fc-cobalt-950': '#172554',
        'fc-saffron-500': '#e86a33',
        'fc-saffron-600': '#d45a2a',
        'fc-gold-400': '#facc15',
        'fc-gold-500': '#d4a017',
        'fc-coral-500': '#ff6b5b',
        'fc-coral-600': '#e85a38',
        'fc-magenta-600': '#c2185b',
        'fc-terracotta-500': '#c65d3b',
        'fc-adobe-600': '#8b5a2b',
        // Template-specific
        'banhmi-yellow': '#f5e100',
        'banhmi-coral': '#ff6b5b',
        'banhmi-black': '#0a0a0a',
        'real-navy': '#1a1a3e',
        'real-saffron': '#e86a33',
        'real-magenta': '#c2185b',
        'real-gold': '#d4a017',
        'real-cream': '#fff8e1',
        'real-creamwhite': '#f5f0e1',
        'misa-cobalt': '#1e5caa',
        'misa-gold': '#d4a017',
        'misa-terracotta': '#c65d3b',
        'misa-adobe': '#8b5a2b',
        'misa-cream': '#f9f5eb',
        // Semantic shortcuts
        'fc-interactive': '#2563eb',
        'fc-interactive-hover': '#1d4ed8',
        'fc-text-primary': '#0a0a0a',
        'fc-text-secondary': '#737373',
        'fc-text-muted': '#a3a3a3',
        'fc-text-inverse': '#ffffff',
        'fc-surface': '#ffffff',
        'fc-background-subtle': '#fafafa',
        'fc-border': '#e5e5e5',
        'fc-success': '#22c55e',
        'fc-success-text': '#15803d',
        'fc-danger': '#ef4444',
        'fc-danger-text': '#b91c1c',
        'fc-warning': '#f59e0b',
        'fc-warning-text': '#b45309',
      },
      fontFamily: {
        display: ['Rubik', 'system-ui', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'sans-serif'],
        body: ['Inter', 'system-ui', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'sans-serif'],
      },
      fontSize: {
        'display-xl': ['clamp(3.5rem, 8vw, 7.5rem)', { lineHeight: '1.1', letterSpacing: '-0.05em', fontWeight: '900' }],
        'display-lg': ['clamp(2.5rem, 5vw, 4.5rem)', { lineHeight: '1.1', letterSpacing: '-0.025em', fontWeight: '800' }],
        'display-md': ['clamp(2rem, 4vw, 3.5rem)', { lineHeight: '1.25', letterSpacing: '-0.025em', fontWeight: '800' }],
      },
      boxShadow: {
        card: '0 4px 20px rgba(0, 0, 0, 0.08)',
        elevated: '0 8px 32px rgba(0, 0, 0, 0.12)',
      },
      borderRadius: {
        '2xl': '1rem',
      },
      animation: {
        'marquee': 'marquee 20s linear infinite',
        'float': 'float 4s ease-in-out infinite',
      },
      keyframes: {
        marquee: {
          '0%': { transform: 'translateX(0)' },
          '100%': { transform: 'translateX(-50%)' },
        },
        float: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-12px)' },
        },
      },
    },
  },
  plugins: [],
}
