import { render, screen, within } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { describe, expect, it, vi } from 'vitest'

import { BillingTimeline, type ClientInvoiceTimelineItem } from '../billing-timeline'

/**
 * C16: the client billing timeline - chronological (newest first by
 * default), sortable, line items expandable per row, totals in the footer.
 */

vi.mock('next/link', () => ({
  default: ({ href, children, ...rest }: { href: string; children: React.ReactNode }) => (
    <a href={href} {...rest}>
      {children}
    </a>
  ),
}))

function invoice(partial: Partial<ClientInvoiceTimelineItem>): ClientInvoiceTimelineItem {
  return {
    id: 1,
    invoiceNumber: 'INV-202607-1',
    status: 'paid',
    year: 2026,
    month: 7,
    isAutoGenerated: true,
    total: '100.00',
    issueDate: '2026-07-01',
    dueDate: '2026-07-16',
    sentAt: '2026-07-01T10:00:00.000Z',
    paidAt: '2026-07-10T10:00:00.000Z',
    lines: [],
    ...partial,
  }
}

const ROWS: ClientInvoiceTimelineItem[] = [
  invoice({
    id: 1,
    total: '100.00',
    lines: [
      {
        id: 11,
        lineType: 'recurring',
        description: 'Monthly Bookkeeping Services',
        quantity: '1.00',
        unitPrice: '100.00',
        discount: '0.00',
        amount: '100.00',
      },
    ],
  }),
  invoice({
    id: 2,
    invoiceNumber: 'INV-202608-1',
    status: 'sent',
    year: 2026,
    month: 8,
    total: '250.00',
    issueDate: '2026-08-01',
    sentAt: '2026-08-02T10:00:00.000Z',
    paidAt: null,
    lines: [
      {
        id: 21,
        lineType: 'recurring',
        description: 'Bank Feed Management',
        quantity: '1.00',
        unitPrice: '100.00',
        discount: '25.00',
        amount: '100.00',
      },
      {
        id: 22,
        lineType: 'other',
        description: 'Preferred Customer Discount',
        quantity: '1.00',
        unitPrice: '-25.00',
        discount: '0.00',
        amount: '-25.00',
      },
    ],
  }),
  // A milestone/progress row: one-off chip, no period tag.
  invoice({
    id: 3,
    invoiceNumber: 'INV-202608-1-C9',
    status: 'draft',
    isAutoGenerated: false,
    total: '2500.00',
    issueDate: '2026-08-01',
    sentAt: null,
  }),
]

describe('BillingTimeline (C16)', () => {
  it('renders newest first with type chips, status, and sent/paid dates', () => {
    render(<BillingTimeline invoices={ROWS} />)
    const rows = screen.getAllByTestId('billing-timeline-row')
    expect(rows).toHaveLength(3)
    // Newest first: the August rows precede July; drafts are fine.
    expect(within(rows[0]).getByText('INV-202608-1-C9')).toBeInTheDocument()
    expect(within(rows[2]).getByText('INV-202607-1')).toBeInTheDocument()
    // Type chips: recurring run vs one-off milestone invoice.
    expect(within(rows[0]).getByText('One-off')).toBeInTheDocument()
    expect(within(rows[2]).getByText('Recurring')).toBeInTheDocument()
    // Status + dates.
    expect(within(rows[1]).getByText('Sent')).toBeInTheDocument()
    expect(within(rows[1]).getByText(/Aug 2, 2026/)).toBeInTheDocument()
    expect(within(rows[2]).getByText(/Paid Jul 10, 2026/)).toBeInTheDocument()
    // Footer totals: void excluded; 3 rows billed 2850, outstanding 250, paid 100.
    const summary = screen.getByTestId('billing-timeline-summary')
    expect(summary).toHaveTextContent('$2,850.00')
    expect(summary).toHaveTextContent('$250.00')
    expect(screen.getByTestId('billing-timeline-totals')).toHaveTextContent('$2,850.00')
  })

  it('sorts by amount on the Total header and back to newest-first on Date', async () => {
    const user = userEvent.setup()
    render(<BillingTimeline invoices={ROWS} />)
    await user.click(screen.getByTestId('sort-total'))
    let rows = screen.getAllByTestId('billing-timeline-row')
    expect(within(rows[0]).getByText('INV-202608-1-C9')).toBeInTheDocument() // 2500 first (desc)
    await user.click(screen.getByTestId('sort-total'))
    rows = screen.getAllByTestId('billing-timeline-row')
    expect(within(rows[0]).getByText('INV-202607-1')).toBeInTheDocument() // 100 first (asc)
    await user.click(screen.getByTestId('sort-date'))
    rows = screen.getAllByTestId('billing-timeline-row')
    expect(within(rows[0]).getByText('INV-202608-1-C9')).toBeInTheDocument()
  })

  it('expands a row into its line items with the discount visible', async () => {
    const user = userEvent.setup()
    render(<BillingTimeline invoices={ROWS} />)
    expect(screen.queryByTestId('billing-timeline-lines')).toBeNull()
    const toggles = screen.getAllByTestId('billing-timeline-expand')
    await user.click(toggles[1]) // INV-202608-1
    const detail = screen.getByTestId('billing-timeline-lines')
    expect(detail).toHaveTextContent('Bank Feed Management')
    expect(detail).toHaveTextContent('Preferred Customer Discount')
    expect(detail).toHaveTextContent('-$25.00')
    expect(toggles[1]).toHaveAttribute('aria-expanded', 'true')
    await user.click(toggles[1])
    expect(screen.queryByTestId('billing-timeline-lines')).toBeNull()
  })
})
