import { sql } from "drizzle-orm";
import {
  boolean,
  date,
  index,
  integer,
  jsonb,
  numeric,
  pgTable,
  serial,
  smallint,
  text,
  timestamp,
  uniqueIndex,
} from "drizzle-orm/pg-core";
import type { AnyPgColumn } from "drizzle-orm/pg-core";

import { invoiceStatusEnum, lineTypeEnum } from "./enums";
import { createdAt, money, updatedAt } from "./shared";
import { clients } from "./clients";
import { tasks } from "./tasks";
import { users } from "./users";

/**
 * Billing (HANDOFF §7 - 3 models; §6.5, §15).
 *
 * The price flows one direction: intake answers → calculate_quote() →
 * recurring_services_template on the client → itemized InvoiceLineItems.
 * Terms are Net 15 from the 1st of the target month; invoices that would
 * end up with no line items are deleted rather than left empty.
 */

export const invoices = pgTable(
  "invoices",
  {
    id: serial("id").primaryKey(),
    clientId: integer("client_id")
      .notNull()
      .references(() => clients.id, { onDelete: "cascade" }),
    invoiceNumber: text("invoice_number"),
    status: invoiceStatusEnum("status").notNull().default("draft"),
    // Accounting period the invoice covers (set on generated invoices; a
    // quarterly-billed client gets one invoice covering three months of work).
    year: integer("year"),
    month: smallint("month"),
    // True for rows from the monthly bulk-generation job (§6.5).
    isAutoGenerated: boolean("is_auto_generated").notNull().default(false),
    issueDate: date("issue_date", { mode: "string" }),
    dueDate: date("due_date", { mode: "string" }), // Net 15 from the 1st
    total: money("total"),
    notes: text("notes"),
    sentAt: timestamp("sent_at", { withTimezone: true, mode: "date" }),
    paidAt: timestamp("paid_at", { withTimezone: true, mode: "date" }),
    voidedAt: timestamp("voided_at", { withTimezone: true, mode: "date" }),
    createdById: integer("created_by_id").references((): AnyPgColumn => users.id),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [
    // §29 fix by construction: the original had no DB-level guard - one
    // generated invoice per (client, period).
    uniqueIndex("invoices_generated_client_period_unique")
      .on(t.clientId, t.year, t.month)
      .where(sql`${t.isAutoGenerated}`),
    uniqueIndex("invoices_number_unique").on(t.invoiceNumber),
    index("invoices_client_status_idx").on(t.clientId, t.status),
    // §15 commission: invoices sent or paid in the month.
    index("invoices_sent_at_idx").on(t.sentAt),
    index("invoices_paid_at_idx").on(t.paidAt),
  ],
);

/**
 * §15 - built from the client's template with quantities recomputed from
 * live data (reconciliation counts exclude merchant and loan account types;
 * discounts aggregate into a single negative line).
 */
export const invoiceLineItems = pgTable(
  "invoice_line_items",
  {
    id: serial("id").primaryKey(),
    invoiceId: integer("invoice_id")
      .notNull()
      .references(() => invoices.id, { onDelete: "cascade" }),
    lineType: lineTypeEnum("line_type").notNull().default("recurring"),
    // Template service key (e.g. account_reconciliations, custom_item_{n},
    // __section_discount__).
    serviceKey: text("service_key"),
    description: text("description").notNull(),
    quantity: numeric("quantity", { precision: 10, scale: 2 }).notNull().default("1"),
    unitPrice: money("unit_price").notNull(),
    discount: money("discount").notNull().default("0"),
    amount: money("amount").notNull(),
    // Completed billable task behind a task line (§6.5).
    taskId: integer("task_id").references(() => tasks.id, { onDelete: "set null" }),
    position: integer("position").notNull().default(0),
    createdAt: createdAt(),
  },
  (t) => [index("invoice_line_items_invoice_idx").on(t.invoiceId)],
);

/** §7 - saved invoice templates (reusable line-item sets per client). */
export const invoiceTemplates = pgTable(
  "invoice_templates",
  {
    id: serial("id").primaryKey(),
    clientId: integer("client_id").references(() => clients.id, { onDelete: "cascade" }),
    name: text("name").notNull(),
    /** Array of line-item shapes mirroring invoice_line_items columns. */
    lineItems: jsonb("line_items").notNull(),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [index("invoice_templates_client_idx").on(t.clientId)],
);
